{{- if .Values.autoscale.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "webapidotnet.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "webapidotnet.name" . }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization        
        averageUtilization: {{ .Values.autoscale.cpu.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.autoscale.memory.targetAverageValue }}
{{- end }}