fullnameOverride: neuappmod-todo

image:
  repository: anujsehgal/neuappmod-dotnet-webapi
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

probes:
  readinessProbe:
    enabled: true
    endpoint: /health/readiness
    initialDelaySeconds: 10
    timeoutSeconds: 20
    periodSeconds: 10

  livenessProbe:
    enabled: true
    endpoint: /health/liveness
    initialDelaySeconds: 10
    timeoutSeconds: 20
    periodSeconds: 10

podSecurityContext: 
  runAsUser: 1000
  runAsGroup: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  
configmapEnv: 
  ASPNETCORE_URLS: "http://*:8080"
  ASPNETCORE_ENVIRONMENT: Docker
  MongoDB__Database: TodoDB
  MongoDB__Host: mongodb.default
  MongoDB__Port: 27017
  MongoDB__User: QfVwGUknc1rY5LvvI4WgPT8fCMNRYW
  MongoDB__Password: 3uf8aPKGobbL1Q3CVDbzYLTcKI2Phl
  

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscale:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 40
  memory:
    targetAverageValue: 200Mi