fullnameOverride: webapidotnet

image:
  repository: anujsehgal/neuappmod-dotnet-webapi
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

probes:
  readinessProbe:
    enabled: false
    endpoint: /
    initialDelaySeconds: 5
    timeoutSeconds: 20
    periodSeconds: 10

  livenessProbe:
    enabled: false
    endpoint: /
    initialDelaySeconds: 5
    timeoutSeconds: 20
    periodSeconds: 10

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  
configmapEnv: 
  ASPNETCORE_URLS: "http://*:8080"
  ASPNETCORE_ENVIRONMENT: "Docker"

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscale:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 40
  memory:
    targetAverageValue: 200Mi