// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: neuservice.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _neuservice_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on NeuRequest with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *NeuRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetInputText()) < 1 {
		return NeuRequestValidationError{
			field:  "InputText",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// NeuRequestValidationError is the validation error returned by
// NeuRequest.Validate if the designated constraints aren't met.
type NeuRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NeuRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NeuRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NeuRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NeuRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NeuRequestValidationError) ErrorName() string { return "NeuRequestValidationError" }

// Error satisfies the builtin error interface
func (e NeuRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNeuRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NeuRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NeuRequestValidationError{}

// Validate checks the field values on NeuResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *NeuResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ReponseText

	return nil
}

// NeuResponseValidationError is the validation error returned by
// NeuResponse.Validate if the designated constraints aren't met.
type NeuResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NeuResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NeuResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NeuResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NeuResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NeuResponseValidationError) ErrorName() string { return "NeuResponseValidationError" }

// Error satisfies the builtin error interface
func (e NeuResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNeuResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NeuResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NeuResponseValidationError{}
