version: '3.4'

services:
  webapi.dotnet:
    image: ${REGISTRY:-neuappmode}/dotnetapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./webapi.dotnet
      dockerfile: Dockerfile
    ports:
      - 5006:8080
    environment:
      ASPNETCORE_URLS: http://*:8080
      ASPNETCORE_ENVIRONMENT: Docker
      MongoDB__Database: TodoDB
      MongoDB__Host: mongo
      MongoDB__Port: 27017
      MongoDB__User: root
      MongoDB__Password: example
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
